/**
 * 
 */
package org.ncbo.stanford.mappings;

/**
 * Mappings generated by the LOOM algorithm, based on close lexical match
 * between preferred names of terms or a preferred name and a synonym. The
 * lexical match involves removing white-space and punctuation from labels. Any
 * labels with no more than 3 characters are excluded.
 * 
 * name: loom
 * 
 * graph: <http://purl.bioontology.org/mapping/loom>
 * 
 * relation: <http://www.w3.org/2004/02/skos/core#closeMatch>
 * 
 * @author dlweber
 * 
 */
final class LoomInfo extends MappingInfo {

	public LoomInfo() {
		super();
		// Use the super() defaults for:
		// mapDate = MappingUtils.xmlDateToday();
		// mappingSourceSite =
		// "<http://www.bioontology.org/wiki/index.php/BioPortal_Mappings>";
		//
		// Note: prior version of loom had user ID: 38342 and 38198.
		// See http://www.bioontology.org/wiki/index.php/LOOM
		// A bioportal user:
		// apiKey = "default-user-api-key";
		// submittedBy = "default-user-id";

		mapGraphName = "loom";
		mapGraphURI = mapGraphNS + mapGraphName;
		mapRelation = "http://www.w3.org/2004/02/skos/core#closeMatch";

		// mapComment = "lexical similarity";
		mappingType = "Automatic";
		mappingSource = "Application";
		mappingSourceName = "NCBO (lexical mapping)";
		mappingSourceContactInfo = "admin@bioontology.org";
		mappingSourceAlgorithm = "Mappings were generated by the LOOM algorithm "
				+ "automatically based on close lexical match between "
				+ "preferred names of terms or a preferred name and a "
				+ "synonym.  The lexical match involves removing white-space "
				+ "and punctuation from labels.  Any labels with no "
				+ "more than 3 characters are excluded.";
	}
}
