#!/bin/bash

mappingInputFile=""
mappingRemoveFile=""
mappingOutputFile=""
mappingsToDelete="mappingsToDelete.ru"

loomGraph='http://purl.bioontology.org/mapping/loom'
loomGraphEncoded=$(php -r "echo rawurlencode('$loomGraph');")
loomBadGraph='http://purl.bioontology.org/mapping/loomBad'
loomBadGraphEncoded=$(php -r "echo rawurlencode('$loomBadGraph');")

# Use a localhost Fuseki server:
export FUSEKI_HOME="$(pwd)/fuseki"
triplestoreURL="http://localhost:3030/loom"
triplestoreUpdateURL="${triplestoreURL}/update"
triplestoreSparqlURL="${triplestoreURL}/query"
triplestoreDataURL="${triplestoreURL}/data"
triplestoreLoomURL="${triplestoreDataURL}/${loomGraph}"
triplestoreLoomBadURL="${triplestoreDataURL}/${loomBadGraph}"

acceptHeader='Accept:text/plain'
tmpFile="tmp.txt"
if [ -f $tmpFile ]; then
    rm $tmpFile
    touch $tmpFile
fi

countMappingIDs () {
    echo >&2
    curl -s \
        -H $acceptHeader \
        --data-urlencode query@sparql_countLoomMappingIDobjects.rq \
        $triplestoreSparqlURL >&2
    curl -s \
        -H $acceptHeader \
        --data-urlencode query@sparql_countLoomMappingIDsubjects.rq \
        $triplestoreSparqlURL >&2
    curl -s \
        -H $acceptHeader \
        --data-urlencode query@sparql_countLoomBadMappingIDs.rq \
        $triplestoreSparqlURL >&2
    echo >&2
}

cleanup () {
    ./runFuseki.sh stop
    rm -f tmp.txt
    rm -f help.txt
    rm -f $mappingsToDelete
}


# ---------------------------------------------------------------------------------
# Process input arguments
#

cat <<END > help.txt

Usage: $0 -i <mappingInputFile.ttl> -s [mappingsRemoveSPARQL.ru] -o [mappingOutputFile.ttl]

The <mappingInputFile.ttl> is generated by java processes.  This input argument
is required.

Unless the [mappingsRemoveSPARQL.ru] file is specified explicitly, the
mappingsToRemove.ru file is used. That file is generated automatically from
mappingsToRemoveAsSPARQL.pl, which parses mappingsToRemove.sql to generate
SPARQL that will populate a new graph with mapping IDs to be removed. The new
graph is temporarily created at: $loomBadGraph

That graph contains triples of the form: ?mapID a
<http://purl.bioontology.org/mapping/mappings.rdfs#One_To_One_Mapping>
The ?mapID is used in a DESCRIBE query on the loom graph to identify all the
loom triples that contain the ?mapID.  This is done by the SPARQL in
sparql_loomMappingsToRemove1.rq and sparql_loomMappingsToRemove2.rq; then all of
those triples are then deleted from the loom graph.

The final result is output to [mappingOutputFile.ttl].  When that argument is not
explicit, the results are placed in <mappingInputFile>_OK.ttl.

END

while getopts ":hi:o:s:" opt; do
    case $opt in
        h)
            cat help.txt >&2
            cleanup
            exit
            ;;
        i)
            mappingInputFile="$OPTARG"
            ;;
        o)
            mappingOutputFile="$OPTARG"
            ;;
        s)
            mappingRemoveFile="$OPTARG"
            echo $mappingRemoveFile
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done

if [ ! -f $mappingInputFile ]; then
    echo "$(date): ERROR: There is no mapping turtle file: $mappingInputFile" >&2
    exit 1;
fi
if [ "$mappingOutputFile" == "" ]; then
    mappingOutputFile=$(echo $mappingInputFile | sed -e "s/\.ttl/_OK\.ttl/")
fi
if [ "$mappingRemoveFile" == "" ]; then
    # No file specified on command line, use a default and verify that
    # it's up-to-date or recreate it.
    mappingRemoveFile="mappingsToRemove.ru"
    perlScript="mappingsToRemoveAsSPARQL.pl"
    perlScriptRun=0
    if [ -f "$mappingRemoveFile" ]; then
        # Run the perl script when the .ru file is older than it.
        if [ "$mappingRemoveFile" -ot "$perlScript" ]; then
            perlScriptRun=1
        fi
    else
        perlScriptRun=1
    fi
    if [ $perlScriptRun -eq 1 ]; then
        if [ ! -f "$perlScript" ]; then
            echo "$(date): ERROR: There is a missing perl script: $perlScript" >&2
            exit 1
        fi
        ./$perlScript > $mappingRemoveFile
        if [ $? -gt 0 ]; then
            echo "$(date): ERROR: Failed to run perl script." >&2
            echo "$(date): ERROR: Failed to create mapping remove SPARQL file: $mappingRemoveFile" >&2
            exit 1
        fi
    fi
fi
if [ ! -f $mappingRemoveFile ]; then
    echo "$(date): ERROR: There is no mapping remove SPARQL file: $mappingRemoveFile" >&2
    exit 1;
fi

echo
echo "input:    $mappingInputFile"
echo "ouput:    $mappingOutputFile"
echo "sparql:   $mappingRemoveFile"
echo

# ---------------------------------------------------------------------------------
# Startup the fuseki SPARQL server (if it's not running already).
./runFuseki.sh start


# ---------------------------------------------------------------------------------
# Ensure we start with a clean slate.
echo >&2
echo "$(date): Starting 'DROP ALL' for loom dataset." >&2
$FUSEKI_HOME/s-update --service $triplestoreUpdateURL "DROP ALL"
if [ $? -eq 0 ]; then
    echo "$(date): Completed 'DROP ALL' for loom dataset." >&2
else
    echo "$(date): Failed to 'DROP ALL' for loom dataset." >&2
    cleanup
    exit 1
fi

# ---------------------------------------------------------------------------------
# Populate the 'loom' graph with the input data.
echo >&2
echo "$(date): Starting upload of new loom graph." >&2
$FUSEKI_HOME/s-put $triplestoreDataURL $loomGraph $mappingInputFile 


if [ $? -eq 0 ]; then
    echo "$(date): Completed upload of new loom graph." >&2
else
    echo "$(date): Failed to upload new loom graph." >&2
    cleanup
    exit 1
fi
countMappingIDs


# ---------------------------------------------------------------------------------
# Remove bad mappings, using SPARQL on the triplestore.  This process requires
# several stages that might be compressed into one stage when 4store has
# implemented full support for the update syntax of SPARQL 1.1; at the moment,
# it cannot support update queries of the form 'DELETE WHERE {}'.  When it can,
# the perl script used to generate mappingsToRemove.ru should be modified so
# this process becomes a one-step update request.
echo >&2
echo "$(date): Starting SPARQL removal of bad loom mappings." >&2
#
# Note: This step is no longer required, because it is completed by the
# 'DROP ALL' update above.
#
## Clear the bad mapping graph.
#$FUSEKI_HOME/s-update --service $triplestoreUpdateURL "DROP GRAPH <${loomBadGraph}>"
#if [ $? -eq 0 ]; then
#    echo "$(date): Completed delete of loomBad graph." >&2
#else
#    echo "$(date): Failed to delete loomBad graph." >&2
#    ./runFuseki.sh stop
#    exit 1
#fi

# Run an update query that will populate a new graph with all the mapping
# IDs that are to be removed.
curl -s -i \
    -o $tmpFile \
    --data-urlencode update@$mappingRemoveFile \
    $triplestoreUpdateURL
grep -q 'error' $tmpFile
if [ $? -eq 0 ]; then
    echo "$(date): Failed to populate loomBad graph." >&2
    cleanup
    exit 1
fi
grep -q '200.*OK' $tmpFile
if [ $? -eq 0 ]; then
    echo "$(date): Completed population of new loomBad graph." >&2
else
    echo "$(date): Failed to populate loomBad graph." >&2
    cleanup
    exit 1
fi
countMappingIDs


# Check the loomBad graph for any content.
# This query returns a count of all the triples in the loomBad graph that match:
# ?mapID a mapRDFS:One_To_One_Mapping .
curl -s \
    -o $tmpFile \
    -H $acceptHeader \
    --data-urlencode query@sparql_countLoomBadMappingIDs.rq \
    $triplestoreSparqlURL 
# Are there are any mappings to be removed?
if [ -s $tmpFile ]; then
    anythingToRemove=$(sed -e "s/[^0-9]//g" tmp.txt | grep '[0-9]')
    if [ $anythingToRemove -eq 0 ]; then
        echo "$(date): There are no bad loom mappings to remove." >&2
        cleanup
        exit
    fi
else
    echo "$(date): There are no bad loom mappings to remove." >&2
    cleanup
    exit
fi

# Continue with removing bad mappings.  

# Use the graph of bad mapping IDs to extract all the triples to be removed from
# the loom graph.  Use a few SPARQL queries to build an update query to remove
# all the bad mappings from loom.  The update query is built in
# $mappingsToDelete.

if [ -f $mappingsToDelete ]; then
    rm $mappingsToDelete
    touch $mappingsToDelete
fi
cat <<END > $mappingsToDelete
DELETE DATA
{
    GRAPH <$loomGraph>
    {
END

# This query returns all the triples with ?mapId as an object in the loom
# graph, which should be only triples with this pattern:
# ?s = <http://purl.bioontology.org/mapping/mappings.rdfs#One_To_One_Mapping> 
# ?p = <http://purl.bioontology.org/mapping/mappings.rdfs#id>
curl -s \
    -o $tmpFile \
    -H $acceptHeader \
    --data-urlencode query@sparql_loomMappingsToRemove1.rq \
    $triplestoreSparqlURL
# Clean up the output of the query
grep '|.*<.*>.*|' $tmpFile | sed -e "s/|//g" -e "s/ $/ \./" >> $mappingsToDelete

# This query returns a description of all the triples 
# with ?mapId as a subject in the loom graph.
curl -s \
    -o $tmpFile \
    -H $acceptHeader \
    --data-urlencode query@sparql_loomMappingsToRemove2.rq  \
    $triplestoreSparqlURL
# Remove the @base, @prefix and empty lines from the $tmpFile file.
grep -v "^@.*$" $tmpFile | grep -v '^\?.*$' >> $mappingsToDelete

# Complete matching braces
cat <<END >> $mappingsToDelete
    }
}
END

# Run an update query to remove all these triples from the loom graph.
curl -s -i \
    -o $tmpFile \
    --data-urlencode update@$mappingsToDelete \
    $triplestoreUpdateURL
grep -q 'error' $tmpFile
if [ $? -eq 0 ]; then
    echo "$(date): Failed to remove bad loom mappings." >&2
    cleanup
    exit 1
fi
grep -q '200.*OK' $tmpFile
if [ $? -eq 0 ]; then
    echo "$(date): Completed SPARQL removal of bad loom mappings." >&2
else
    echo "$(date): Failed to remove bad loom mappings." >&2
    cleanup
    exit 1
fi
countMappingIDs


# Clear the bad mapping graph.
$FUSEKI_HOME/s-update --service $triplestoreUpdateURL "DROP GRAPH <${loomBadGraph}>"
if [ $? -eq 0 ]; then
    echo "$(date): Completed delete of loomBad graph." >&2
else
    echo "$(date): Failed to delete loomBad graph." >&2
    cleanup
    exit 1
fi

# ---------------------------------------------------------------------------------
# This query returns all the 'good' triples in the loom graph.
echo >&2
echo "$(date): Starting SPARQL dump for all good loom mappings." >&2
$FUSEKI_HOME/s-get $triplestoreDataURL $loomGraph > $mappingOutputFile
if [ $? -eq 0 ]; then
    echo "$(date): Completed SPARQL dump for all good loom mappings: $mappingOutputFile" >&2
else
    echo "$(date): Failed SPARQL dump for all good loom mappings" >&2
    cleanup
    exit 1
fi

cleanup

